#!/bin/bash


RED='\033[1;31m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m' # No Color


blacklist=()
blacklistFile="${REPOS}/rrpullblacklist.txt"

if [ ! -f "${blacklistFile}" ]; then
    echo -e "[rrpull    ] ${RED}rrpullblacklist.txt not found${NC}"
else
    echo "[rrpull    ] Blacklisted directories:"
    while IFS= read -r line; do
        blacklist+=("${REPOS}${line}")
        echo -e "[rrpull    ]    ${REPOS}${RED}${line}${NC}"
    done < $blacklistFile
fi


isBlacklisted() {
    local normCheckPath=$(readlink -f "$1")
    local normBlackPath=()

    for blacklisted in "${blacklist[@]}"; do
        normBlackPath=$(readlink -f "${blacklisted}")
        if [[ "${normCheckPath}" == "${normBlackPath}" || "${normCheckPath}" == "${normBlackPath}"/* ]]; then
            return 0
        fi
    done

    return 1
}


find "${REPOS}" -name ".git" -type d | while read -r gitdir; do
    repoPath="${gitdir%/.git}"
    normRepoPath=$(readlink -f "$repoPath")

    if ! isBlacklisted "${repoPath}"; then
        echo "----------------------------------------------------------------------------------------------------"
        echo -e "[rrpull    ] ${BLUE}Pulling ${normRepoPath}${NC}"
        (cd "${repoPath}" && git pull 2>&1 | sed 's/^/[rrpull git]    /')
    else
        echo "----------------------------------------------------------------------------------------------------"
        echo -e "[rrpull    ] ${YELLOW}Skipping blacklisted repo: ${normRepoPath}${NC}"
    fi
done
